### ISSUE TITLE
installing question: errors in the scons step

### ISSUE THREAD

**Issue by Dnepropetrovst** [underworldcode/underworld1#4]
Hello, i am trying to install the underworld1. when I run `./scons.py,` and the terminal shows as follows:

`scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Compiling ==> PICellerator/Common/src/Ppc.c
PICellerator/Common/src/Ppc.c: In function ‘_Ppc_AssignFromXML’:
PICellerator/Common/src/Ppc.c:57:14: warning: variable ‘theDictionary’ set but not used [-Wunused-but-set-variable]
  Dictionary* theDictionary = NULL;
              ^~~~~~~~~~~~~
PICellerator/Common/src/Ppc.c: In function ‘Ppc_Get’:
PICellerator/Common/src/Ppc.c:182:4: error: non-floating-point argument in call to function ‘__builtin_isinf_sign’
    assert( isnan(result[0]) == 0 || isinf((float)result[0] != 0 ));
    ^~~~~~
PICellerator/Common/src/Ppc.c:182:4: error: non-floating-point argument in call to function ‘__builtin_isinf_sign’
PICellerator/Common/src/Ppc.c: In function ‘_Ppc_VariableConditionFunction’:
PICellerator/Common/src/Ppc.c:225:76: warning: passing argument 4 of ‘FeMesh_CoordGlobalToLocal’ from incompatible pointer type [-Wincompatible-pointer-types]
 _CoordGlobalToLocal( self->manager->mesh, elements[0], coordGlobal, &(intPoint.xi) );
                                                                     ^
In file included from build/include/StgFEM/Discretisation/Discretisation.h:86:0,
                 from build/include/StgFEM/StgFEM.h:55,
                 from PICellerator/Common/src/Ppc.c:4:
build/include/StgFEM/Discretisation/FeMesh.h:129:7: note: expected ‘double *’ but argument is of type ‘double (*)[3]’
  void FeMesh_CoordGlobalToLocal( void* feMesh, unsigned element, double* global, double* local );
       ^~~~~~~~~~~~~~~~~~~~~~~~~
scons: *** [build/PICellerator/Common/src/Ppc.os] Error 1
scons: building terminated because of errors.`

Could anyone tell me how to solve this problem?
In advance many thanks for any suggestion!

**Comment by julesghub** [comment]
Hi @Dnepropetrovst, underworld1 is no longer being developed. That's why we have Underworld2 ;) I suggest you use uw2 as it's much easier to use and install.

That said the above error is a syntax error. The ')' character is incorrect and the compiler is complaining about it.
This error is happening on line `181` in this repository, but line `182` is mentioned in your error message. 
Are you using the code in this repository?

**Comment by julesghub** [comment]
Closing this ticket due to inactivity. Feel free to reopen @Dnepropetrovst
